### PR TITLE
Added support for more metrics

### PR DESCRIPTION
**Pull request by malston**

### CODE REVIEW

**Comment by simonjohansson** [comment]
Great! Nice cleanup :)

Just a couple of questions.

1. Does this fully work on a non-Diego installation?
2. Is there a reason why ContainerMetrics are not run within goroutins?

**Comment by simonjohansson** [comment]
Ah, regarding ContainerMetrics not runnin in a goroutine, I see why :)

I had a quick comparisson between this fork and the current stable. (Running for ~1min at the same time with different subscription-id's)

```
➜  firehose-to-syslog git:(refactor) ✗ ./firehose-to-syslog ..... &> /tmp/fork
^C%                                                                                                                                                                  ➜  firehose-to-syslog git:(refactor) ✗ wc -l /tmp/fork
978 /tmp/fork
➜  firehose-to-syslog git:(refactor) ✗ egrep -oh '"source_type":"([a-zA-Z]+)"' /tmp/fork | sort | uniq -c
      1 "source_type":"API"
    361 "source_type":"App"
      3 "source_type":"DEA"
    177 "source_type":"RTR"
```
ValueMetric
```
➜  firehose-to-syslog git:(master) ✗ ./firehose-to-syslog .....  &> /tmp/master
^C%                                                                                                                                                                  ➜  firehose-to-syslog git:(master) ✗ wc -l /tmp/orig 
3176 /tmp/orig
➜  firehose-to-syslog git:(master) ✗ egrep -oh '"source_type":"([a-zA-Z]+)"' /tmp/orig | sort | uniq -c
     11 "source_type":"API"
   2187 "source_type":"App"
     10 "source_type":"DEA"
    961 "source_type":"RTR"
      4 "source_type":"STG"
```
Reason I used source_type to grep is because LogMessages in the fork is the same as in Master.

**Comment by malston** [comment]
Hmm... that's a really interesting comparison. I'll run the same test to see if I get the same results. I'll see if I can track down the issue. I'm in the process of setting up lattice. So to answer your other question, I haven't tested on diego to see the container metrics. I'm expecting I can do that with lattice. I'll keep you posted.

**Comment by malston** [comment]
Ok... I got the same results and from what I see it appears that there are messages that are not being filtered from the stream in the master that are filtered from the fork. I'm seeing a bunch of messages like with a `"message_type":"OUT"` which when I add a default to the switch that reads from the firehose channel show up in the fork as well. 
screen shot 2015-03-31 at 3 13 02 pm

**Comment by shinji62** [comment]
What about merging this one, and start to work on container metrics afterward.

**Comment by malston** [comment]
Since I was using separate buffered channels for each event type, the senders were getting blocked until a message was received causing message loss. The above commits addresses this issue.

**Comment by simonjohansson** [comment]
Lovely, now the numbers match up!
Will merge today.

**Comment by simonjohansson** [comment]
@malston @shinji62 I have merged this into the develop branch of the project.

Thanks again @malston for the PR.

**Pull request closed without merging**
